name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Push docs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        name: build docs
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        with:
          command: doc
          args: --all --all-features --no-deps

      - uses: peaceiris/actions-gh-pages@v3
        name: push docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          keep_files: true
